### ISSUE TITLE
It is not visible

### ISSUE THREAD

**Issue by Ashish1323** [Juanescacha/FullStackOpen-2022#2]
https://github.com/Juanescacha/FullStackOpen-2022/blob/1b889f4902dc91d369e2ebbba9aed006dcd1bf7e/README.md?plain=1#L1

**Comment by Juanescacha** [comment]
Hi! what you mean it's not visible the certificate image?

on the Readme.md of the repo, I see it.

![image](https://user-images.githubusercontent.com/6394715/217071932-3b2a9b65-418d-49d6-8e95-4c155a42206a.png)

**Comment by Juanescacha** [comment]
@Ashish1323 hellow?
